FROM tensorflow/tensorflow:1.10.0-gpu-py3

COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt
COPY . /retinanet
RUN python /retinanet/setup.py build_ext --inplace

WORKDIR "/srv"
CMD ["tensorboard", "--logdir=/srv/logs/train"]
