FROM tensorflow/tensorflow:1.10.0-gpu

COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
COPY . /retinanet
RUN cd /retinanet && python /retinanet/setup.py build_ext --inplace

WORKDIR "/srv"
CMD ["tensorboard", "--logdir=/srv/logs/train"]
